-- 이메일 알림 기능: notification_preferences에 이메일 수신 여부 컬럼 추가
-- 옵트아웃 방식: 기본값 true (설정 행이 없는 유저도 발송 로직에서 켜짐으로 간주)
-- Supabase 대시보드 > SQL Editor에서 실행하세요.

ALTER TABLE notification_preferences
  ADD COLUMN IF NOT EXISTS email_enabled boolean NOT NULL DEFAULT true;

-- 이전 버전(DEFAULT false)으로 이미 실행했던 경우를 위한 보정
ALTER TABLE notification_preferences
  ALTER COLUMN email_enabled SET DEFAULT true;

UPDATE notification_preferences SET email_enabled = true WHERE email_enabled = false;

-- 장부 멤버에 이메일 등록 (계정 가입 없이도 충전 요청 메일 직접 발송)
ALTER TABLE members
  ADD COLUMN IF NOT EXISTS email text;

-- 이메일 발송 이력 (실패 원인 추적용, service role만 접근)
CREATE TABLE IF NOT EXISTS email_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id uuid,
  type text NOT NULL,          -- order_registered | low_balance | charge_request | custom | manual | invite
  recipient text NOT NULL,
  subject text,
  success boolean NOT NULL DEFAULT true,
  error text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS email_logs_company_created_idx
  ON email_logs (company_id, created_at DESC);

-- 정책 없이 RLS만 켜서 클라이언트 접근 차단 (서버의 service role만 읽기/쓰기)
ALTER TABLE email_logs ENABLE ROW LEVEL SECURITY;

-- 주문 등록 이메일은 발송량이 많아 기본 꺼짐 (원하는 유저만 옵트인)
ALTER TABLE notification_preferences
  ADD COLUMN IF NOT EXISTS order_email_enabled boolean NOT NULL DEFAULT false;
